# Generated by Django 6.0.6 on 2026-07-03 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_song_audio_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='duration',
            field=models.CharField(default='0:00', help_text='Formato MM:SS (es. 3:45)', max_length=10),
        ),
    ]
